<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Oindrila Sen" />


<title>Airbnb-To understand how the different features of a listing in LA can influence the price</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="libs/highlightjs-1.1/highlight.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Airbnb-To understand how the different features of a listing in LA can influence the price</h1>
<h4 class="author"><em>Oindrila Sen</em></h4>
<h4 class="date"><em>November,20, 2017</em></h4>

</div>


<hr />
<div id="prologue" class="section level1">
<h1><span class="header-section-number">1</span> Prologue</h1>
<p><em>“Airbnb happened because two guys could not pay their rent, but did have some space.”</em> <br><br> Yes, that’s how Air-bed and breakfast(Airbnb) started when Joe and Martin from San Francisco rented out their three airbeds to make some cash.Since then, guests and hosts have used Airbnb to travel in a more unique and personalized way.The story of Airbnb’s foundation is fascinating and is here: <a href="http://www.airbnb.com/home/story">airbnb</a>. <br><br> Airbnb is a hospitality service which enables people to lease or rent a short-term accommodation.The company does not own any lodging. It is merely an agent.It receives a percentage service fees (commissions) from both guests and hosts for every booking.<br />
<br> A Host can create a listing by selecting the “Host” menu after logging in.The Price for the listing is decided by the host himself. The owner can charge different prices for nightly, weekly, and monthly stays. Hosts then add a description of the residence, amenities, available dates, cancellation policies, and any house rules.Potential guests are required to message the host directly through Airbnb to ask questions regarding the property.After the reservation, the hosts coordinate meeting times and contact information with the guests. Airbnb guests can leave a review and rate a listing after their stay.This rating can be used as an indicator of the experience they had during their stay. <br> Airbnb was started small and soon the concept turned out to be popular among those people who were on the verge of losing their homes due to financial difficulties and also the travelers who are looking for a home away from home. <a href="https://en.wikipedia.org/wiki/Airbnb">Wiki</a> is always there for more information.</p>
</div>
<div id="problem-setup" class="section level1">
<h1><span class="header-section-number">2</span> Problem Setup</h1>
<p>In this project, I am working on the Los Angeles based Airbnb listings.<br />
My objective is to understand how the different features can influence the price for a listing in LA.<br />
I would provide a tool to estimate the price of a listing in LA based on its features.<br />
<br> Thus, to summarize, this Capstone Project will answer the below questions: <br> 1. How the different attributes/features can influence the price for a Airbnb listing in LA?<br />
2. What price would be suitable for a new listing in LA?<br />
3. How the price of a listing is affecting the Review Rating?</p>
</div>
<div id="potential-client" class="section level1">
<h1><span class="header-section-number">3</span> Potential client</h1>
<ol style="list-style-type: decimal">
<li>A new host who is looking for some recommendation for the price he should list for his property<br />
</li>
<li>Or, Someone who is willing to list his property in Airbnb site in Los Angeles and gathering information on what are the factors that would affect the price for a listing<br />
</li>
<li>Or, an existing host who already has an Airbnb listing in LA and looking for a revision in price to get more customers and better reviews.</li>
</ol>
</div>
<div id="the-data" class="section level1">
<h1><span class="header-section-number">4</span> The Data</h1>
<p>I am going to use the datasets loaded in <a href="http://insideairbnb.com/get-the-data.html">insideairbnb</a> for Los Angeles, California. The latest data sets are added on May,2017. The below datasets are included: <br> 1. Detail_Listings.csv<br />
2. Summary_Listings<br />
3. Detail_Reviews.csv<br />
4. Summary_Reviews.csv<br />
5. Calendar.csv<br />
6. Neighbourhoods.csv<br />
<br> For this project, I will use the “Detail_Listings.csv” file alone.This Data file has 31253 records with 1 record for each individual listing.There are 95 columns representing different features for each listing.</p>
<p>Below is a glimpse of the “Detail_listings.csv” data file:</p>
<pre class="r"><code>glimpse(Detail_listing)</code></pre>
<pre><code>## Observations: 31,253
## Variables: 95
## $ id                               &lt;int&gt; 16228948, 8909380, 14078522, ...
## $ listing_url                      &lt;chr&gt; &quot;https://www.airbnb.com/rooms...
## $ scrape_id                        &lt;dbl&gt; 2.01705e+13, 2.01705e+13, 2.0...
## $ last_scraped                     &lt;chr&gt; &quot;2017-05-03&quot;, &quot;2017-05-03&quot;, &quot;...
## $ name                             &lt;chr&gt; &quot;Robert Ranch in Los Angeles ...
## $ summary                          &lt;chr&gt; &quot;Stunning Ranch Estate situat...
## $ space                            &lt;chr&gt; NA, &quot;Very private and quite ....
## $ description                      &lt;chr&gt; &quot;Stunning Ranch Estate situat...
## $ experiences_offered              &lt;chr&gt; &quot;none&quot;, &quot;none&quot;, &quot;none&quot;, &quot;none...
## $ neighborhood_overview            &lt;chr&gt; NA, &quot;I&#39;m in the country what&#39;...
## $ notes                            &lt;chr&gt; NA, NA, &quot;Overnight stalls for...
## $ transit                          &lt;chr&gt; NA, &quot;The train station is onl...
## $ access                           &lt;chr&gt; NA, &quot;Whole house&quot;, &quot;Private B...
## $ interaction                      &lt;chr&gt; NA, &quot;As much or as little as ...
## $ house_rules                      &lt;chr&gt; &quot;- No noise/music outside all...
## $ thumbnail_url                    &lt;chr&gt; NA, &quot;https://a0.muscache.com/...
## $ medium_url                       &lt;chr&gt; NA, &quot;https://a0.muscache.com/...
## $ picture_url                      &lt;chr&gt; &quot;https://a0.muscache.com/im/p...
## $ xl_picture_url                   &lt;chr&gt; NA, &quot;https://a0.muscache.com/...
## $ host_id                          &lt;int&gt; 54345288, 44800067, 84615808,...
## $ host_url                         &lt;chr&gt; &quot;https://www.airbnb.com/users...
## $ host_name                        &lt;chr&gt; &quot;Robert&quot;, &quot;Kevin&quot;, &quot;Kirsten&quot;,...
## $ host_since                       &lt;chr&gt; &quot;2016-01-12&quot;, &quot;2015-09-22&quot;, &quot;...
## $ host_location                    &lt;chr&gt; &quot;Los Angeles, California, Uni...
## $ host_about                       &lt;chr&gt; &quot;Thank You for considering my...
## $ host_response_time               &lt;chr&gt; &quot;a few days or more&quot;, &quot;within...
## $ host_response_rate               &lt;chr&gt; &quot;25%&quot;, &quot;100%&quot;, &quot;100%&quot;, &quot;100%&quot;...
## $ host_acceptance_rate             &lt;chr&gt; &quot;N/A&quot;, &quot;N/A&quot;, &quot;N/A&quot;, &quot;N/A&quot;, &quot;...
## $ host_is_superhost                &lt;chr&gt; &quot;f&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;f&quot;, &quot;f&quot;,...
## $ host_thumbnail_url               &lt;chr&gt; &quot;https://a0.muscache.com/im/p...
## $ host_picture_url                 &lt;chr&gt; &quot;https://a0.muscache.com/im/p...
## $ host_neighbourhood               &lt;chr&gt; NA, NA, NA, NA, &quot;West Adams&quot;,...
## $ host_listings_count              &lt;int&gt; 1, 1, 1, 1, 1, 1, 2, 23, 1, 2...
## $ host_total_listings_count        &lt;int&gt; 1, 1, 1, 1, 1, 1, 2, 23, 1, 2...
## $ host_verifications               &lt;chr&gt; &quot;[&#39;email&#39;, &#39;phone&#39;, &#39;reviews&#39;...
## $ host_has_profile_pic             &lt;chr&gt; &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;,...
## $ host_identity_verified           &lt;chr&gt; &quot;f&quot;, &quot;f&quot;, &quot;t&quot;, &quot;f&quot;, &quot;t&quot;, &quot;f&quot;,...
## $ street                           &lt;chr&gt; &quot;Acton, CA 93510, United Stat...
## $ neighbourhood                    &lt;chr&gt; NA, NA, NA, NA, &quot;West Adams&quot;,...
## $ neighbourhood_cleansed           &lt;chr&gt; &quot;Acton&quot;, &quot;Acton&quot;, &quot;Acton&quot;, &quot;A...
## $ neighbourhood_group_cleansed     &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, N...
## $ city                             &lt;chr&gt; &quot;Acton&quot;, &quot;Palmdale&quot;, &quot;Acton&quot;,...
## $ state                            &lt;chr&gt; &quot;CA&quot;, &quot;CA&quot;, &quot;CA&quot;, &quot;CA&quot;, &quot;CA&quot;,...
## $ zipcode                          &lt;chr&gt; &quot;93510&quot;, &quot;93550&quot;, &quot;93510&quot;, &quot;9...
## $ market                           &lt;chr&gt; &quot;Other (Domestic)&quot;, &quot;Other (D...
## $ smart_location                   &lt;chr&gt; &quot;Acton, CA&quot;, &quot;Palmdale, CA&quot;, ...
## $ country_code                     &lt;chr&gt; &quot;US&quot;, &quot;US&quot;, &quot;US&quot;, &quot;US&quot;, &quot;US&quot;,...
## $ country                          &lt;chr&gt; &quot;United States&quot;, &quot;United Stat...
## $ latitude                         &lt;dbl&gt; 34.53035, 34.48543, 34.51013,...
## $ longitude                        &lt;dbl&gt; -118.2271, -118.1254, -118.21...
## $ is_location_exact                &lt;chr&gt; &quot;t&quot;, &quot;f&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;,...
## $ property_type                    &lt;chr&gt; &quot;House&quot;, &quot;House&quot;, &quot;House&quot;, &quot;O...
## $ room_type                        &lt;chr&gt; &quot;Entire home/apt&quot;, &quot;Private r...
## $ accommodates                     &lt;int&gt; 10, 2, 2, 6, 1, 1, 2, 2, 2, 2...
## $ bathrooms                        &lt;dbl&gt; 7.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
## $ bedrooms                         &lt;int&gt; 5, 1, 1, 1, 1, 1, 1, 1, 2, 1,...
## $ beds                             &lt;int&gt; 5, 1, 1, 3, 1, 1, 1, 1, 1, 2,...
## $ bed_type                         &lt;chr&gt; &quot;Real Bed&quot;, &quot;Real Bed&quot;, &quot;Real...
## $ amenities                        &lt;chr&gt; &quot;{\&quot;Wireless Internet\&quot;,\&quot;Air...
## $ square_feet                      &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, N...
## $ price                            &lt;chr&gt; &quot;$3,000.00&quot;, &quot;$50.00&quot;, &quot;$55.0...
## $ weekly_price                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, &quot;...
## $ monthly_price                    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, &quot;...
## $ security_deposit                 &lt;chr&gt; &quot;$2,000.00&quot;, NA, NA, NA, NA, ...
## $ cleaning_fee                     &lt;chr&gt; &quot;$200.00&quot;, NA, NA, &quot;$35.00&quot;, ...
## $ guests_included                  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
## $ extra_people                     &lt;chr&gt; &quot;$0.00&quot;, &quot;$0.00&quot;, &quot;$10.00&quot;, &quot;...
## $ minimum_nights                   &lt;int&gt; 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,...
## $ maximum_nights                   &lt;int&gt; 1125, 1125, 1125, 2, 90, 1125...
## $ calendar_updated                 &lt;chr&gt; &quot;5 months ago&quot;, &quot;2 months ago...
## $ has_availability                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, N...
## $ availability_30                  &lt;int&gt; 27, 29, 18, 3, 0, 4, 6, 22, 2...
## $ availability_60                  &lt;int&gt; 53, 45, 43, 17, 0, 17, 21, 52...
## $ availability_90                  &lt;int&gt; 82, 75, 73, 30, 0, 32, 42, 82...
## $ availability_365                 &lt;int&gt; 352, 350, 348, 87, 0, 32, 42,...
## $ calendar_last_scraped            &lt;chr&gt; &quot;2017-05-03&quot;, &quot;2017-05-03&quot;, &quot;...
## $ number_of_reviews                &lt;int&gt; 0, 33, 14, 22, 3, 0, 38, 23, ...
## $ first_review                     &lt;chr&gt; NA, &quot;2015-12-04&quot;, &quot;2016-09-02...
## $ last_review                      &lt;chr&gt; NA, &quot;2017-04-22&quot;, &quot;2017-04-29...
## $ review_scores_rating             &lt;int&gt; NA, 93, 100, 100, 93, NA, 98,...
## $ review_scores_accuracy           &lt;int&gt; NA, 10, 10, 10, 10, NA, 10, 9...
## $ review_scores_cleanliness        &lt;int&gt; NA, 10, 10, 10, 9, NA, 10, 8,...
## $ review_scores_checkin            &lt;int&gt; NA, 10, 10, 10, 10, NA, 10, 9...
## $ review_scores_communication      &lt;int&gt; NA, 10, 10, 10, 10, NA, 10, 9...
## $ review_scores_location           &lt;int&gt; NA, 9, 10, 10, 9, NA, 10, 8, ...
## $ review_scores_value              &lt;int&gt; NA, 9, 10, 10, 10, NA, 10, 9,...
## $ requires_license                 &lt;chr&gt; &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;,...
## $ license                          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N...
## $ jurisdiction_names               &lt;chr&gt; NA, NA, NA, NA, &quot;City of Los ...
## $ instant_bookable                 &lt;chr&gt; &quot;t&quot;, &quot;f&quot;, &quot;f&quot;, &quot;t&quot;, &quot;f&quot;, &quot;f&quot;,...
## $ cancellation_policy              &lt;chr&gt; &quot;strict&quot;, &quot;flexible&quot;, &quot;flexib...
## $ require_guest_profile_picture    &lt;chr&gt; &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;,...
## $ require_guest_phone_verification &lt;chr&gt; &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;,...
## $ calculated_host_listings_count   &lt;int&gt; 1, 1, 1, 1, 1, 1, 2, 19, 1, 2...
## $ reviews_per_month                &lt;dbl&gt; NA, 1.91, 1.72, 2.12, 0.18, N...</code></pre>
<pre class="r"><code>dim(Detail_listing)</code></pre>
<pre><code>## [1] 31253    95</code></pre>
</div>
<div id="data-wrangling-and-cleaning" class="section level1">
<h1><span class="header-section-number">5</span> Data Wrangling and Cleaning</h1>
<p>“Detail_Listings.csv” Dataset contains 95 columns. I will remove some of the columns that won’t be useful based on the goals I have for this project. I would be using the below columns from the Dataset:</p>
<pre class="r"><code>glimpse(clean_listing)</code></pre>
<pre><code>## Observations: 31,253
## Variables: 23
## $ id                     &lt;int&gt; 16228948, 8909380, 14078522, 13006928, ...
## $ accommodates           &lt;int&gt; 10, 2, 2, 6, 1, 1, 2, 2, 2, 2, 2, 3, 1,...
## $ host_response_rate     &lt;chr&gt; &quot;25%&quot;, &quot;100%&quot;, &quot;100%&quot;, &quot;100%&quot;, &quot;N/A&quot;, &quot;...
## $ host_is_superhost      &lt;chr&gt; &quot;f&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;f&quot;, &quot;f&quot;, &quot;t&quot;, &quot;f&quot;,...
## $ host_has_profile_pic   &lt;chr&gt; &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;, &quot;t&quot;,...
## $ host_identity_verified &lt;chr&gt; &quot;f&quot;, &quot;f&quot;, &quot;t&quot;, &quot;f&quot;, &quot;t&quot;, &quot;f&quot;, &quot;t&quot;, &quot;t&quot;,...
## $ host_listings_count    &lt;int&gt; 1, 1, 1, 1, 1, 1, 2, 23, 1, 2, 1, 2, 23...
## $ instant_bookable       &lt;chr&gt; &quot;t&quot;, &quot;f&quot;, &quot;f&quot;, &quot;t&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;,...
## $ property_type          &lt;chr&gt; &quot;House&quot;, &quot;House&quot;, &quot;House&quot;, &quot;Other&quot;, &quot;Ap...
## $ room_type              &lt;chr&gt; &quot;Entire home/apt&quot;, &quot;Private room&quot;, &quot;Pri...
## $ bathrooms              &lt;dbl&gt; 7.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, NA, ...
## $ bedrooms               &lt;int&gt; 5, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, ...
## $ beds                   &lt;int&gt; 5, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1, 2, 1, ...
## $ bed_type               &lt;chr&gt; &quot;Real Bed&quot;, &quot;Real Bed&quot;, &quot;Real Bed&quot;, &quot;Re...
## $ cancellation_policy    &lt;chr&gt; &quot;strict&quot;, &quot;flexible&quot;, &quot;flexible&quot;, &quot;flex...
## $ availability_365       &lt;int&gt; 352, 350, 348, 87, 0, 32, 42, 357, 364,...
## $ price                  &lt;chr&gt; &quot;$3,000.00&quot;, &quot;$50.00&quot;, &quot;$55.00&quot;, &quot;$150....
## $ weekly_price           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, &quot;$320.00&quot;, ...
## $ monthly_price          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, &quot;$999.00&quot;, ...
## $ cleaning_fee           &lt;chr&gt; &quot;$200.00&quot;, NA, NA, &quot;$35.00&quot;, &quot;$5.00&quot;, N...
## $ security_deposit       &lt;chr&gt; &quot;$2,000.00&quot;, NA, NA, NA, NA, NA, NA, NA...
## $ number_of_reviews      &lt;int&gt; 0, 33, 14, 22, 3, 0, 38, 23, 0, 42, 15,...
## $ review_scores_rating   &lt;int&gt; NA, 93, 100, 100, 93, NA, 98, 89, NA, 9...</code></pre>
<p><br> Now, my current Dataset has 23 variables for 31,253 observations. I need to clean the data for further analysis.<br />
<br> 1. The Price columns are of “Char” data type and contains a Dollar sign and a comma. I need to remove the “‘$’” and “,” and then convert them into a Numeric variable for my analysis. Below are the price columns that I would be using: <br> * price<br />
* weekly_price<br />
* monthly_price<br />
* cleaning_fee<br />
* security_deposit<br />
<br></p>
<pre class="r"><code>#Remove &quot;$&quot; and &quot;,&quot; from the price columns
# Transforming prices to number
clean_listing$price &lt;-
  gsub(&quot;\\$&quot;, replacement = &quot;&quot;, clean_listing$price)
clean_listing$price &lt;-
  gsub(&quot;,&quot;, replacement = &quot;&quot;, clean_listing$price)
clean_listing$price &lt;- as.numeric(clean_listing$price)

clean_listing$security_deposit &lt;-
  gsub(&quot;\\$&quot;, replacement = &quot;&quot;, clean_listing$security_deposit)
clean_listing$security_deposit &lt;-
  gsub(&quot;,&quot;, replacement = &quot;&quot;, clean_listing$security_deposit)
clean_listing$security_deposit &lt;-
  as.numeric(clean_listing$security_deposit)

clean_listing$cleaning_fee &lt;-
  gsub(&quot;\\$&quot;, replacement = &quot;&quot;, clean_listing$cleaning_fee)
clean_listing$cleaning_fee &lt;-
  gsub(&quot;,&quot;, replacement = &quot;&quot;, clean_listing$cleaning_fee)
clean_listing$cleaning_fee &lt;- as.numeric(clean_listing$cleaning_fee)

clean_listing$weekly_price &lt;-
  gsub(&quot;\\$&quot;, replacement = &quot;&quot;, clean_listing$weekly_price)
clean_listing$weekly_price &lt;-
  gsub(&quot;,&quot;, replacement = &quot;&quot;, clean_listing$weekly_price)
clean_listing$weekly_price &lt;- as.numeric(clean_listing$weekly_price)

clean_listing$monthly_price &lt;-
  gsub(&quot;\\$&quot;, replacement = &quot;&quot;, clean_listing$monthly_price)
clean_listing$monthly_price &lt;-
  gsub(&quot;,&quot;, replacement = &quot;&quot;, clean_listing$monthly_price)
clean_listing$monthly_price &lt;-
  as.numeric(clean_listing$monthly_price)</code></pre>
<p><br> 2. The Categorical Variables need to be converted into Factors. Below are the Variables that needs to be converted to Factors:<br />
* host_response_rate<br />
* host_is_superhost<br />
* host_identity_verified * host_has_profile_pic<br />
* instant_bookable<br />
* property_type<br />
* room_type<br />
* bed_type<br />
* cancellation_policy <br></p>
<pre class="r"><code># Transforming to factors:
to_factor &lt;- c(
  &#39;host_has_profile_pic&#39;,
  &#39;host_response_rate&#39;,
  &#39;host_is_superhost&#39;,
  &#39;instant_bookable&#39;,
  &#39;host_identity_verified&#39;,
  &#39;property_type&#39;,
  &#39;room_type&#39;,
  &#39;bed_type&#39;,
  &#39;cancellation_policy&#39;
)
for (col in to_factor) {
  clean_listing[[col]] &lt;- factor(clean_listing[[col]])
}</code></pre>
<p><br> 3. Before proceeding further, let’s deal with the ‘NA’ Values. First, let’s find out how many ‘NA’ values we have for each variable and below is the result:<br />
<br></p>
<pre class="r"><code>sapply(clean_listing, function (x) sum(is.na(x)))</code></pre>
<pre><code>##                     id           accommodates     host_response_rate 
##                      0                      0                     14 
##      host_is_superhost   host_has_profile_pic host_identity_verified 
##                     14                     14                     14 
##    host_listings_count       instant_bookable          property_type 
##                     14                      0                      0 
##              room_type              bathrooms               bedrooms 
##                      0                     97                     35 
##                   beds               bed_type    cancellation_policy 
##                     59                      0                      0 
##       availability_365                  price           weekly_price 
##                      0                      0                  23823 
##          monthly_price           cleaning_fee       security_deposit 
##                  24620                   6974                  14397 
##      number_of_reviews   review_scores_rating 
##                      0                   7527</code></pre>
<ul>
<li>host_is_superhost:<br />
This Variable has categorical values TRUE and FALSE. So, let’s assume the NA records are FALSE i.e. The records for which a value is not there is not a Super Host.</li>
</ul>
<pre class="r"><code>## Assuming that NAs in the host_is_superhost columns are False
clean_listing$host_is_superhost[is.na(clean_listing$host_is_superhost)] &lt;- &quot;f&quot;</code></pre>
<ul>
<li>Bedrooms,Bathrooms &amp; Beds:<br />
For Bedrooms, Bathrooms and Beds variables, there are a coulple of NA records. These variable are nemerical and let’s replace the NA value with the most common value for that variable.</li>
</ul>
<pre class="r"><code>## Replacing the NAs with the MEAN value of that column
table(clean_listing$bedrooms)</code></pre>
<pre><code>## 
##     0     1     2     3     4     5     6     7     8     9    10 
##  2937 19937  4868  2197   812   297    96    45     9    12     8</code></pre>
<pre class="r"><code>clean_listing$bedrooms[is.na(clean_listing$bedrooms)] &lt;- 1

table(clean_listing$bathrooms) </code></pre>
<pre><code>## 
##     0   0.5     1   1.5     2   2.5     3   3.5     4   4.5     5   5.5 
##   138   162 21969  1530  4601   866   893   311   250   115    76    68 
##     6   6.5     7   7.5     8 
##    35    18    27    20    77</code></pre>
<pre class="r"><code>clean_listing$bathrooms[is.na(clean_listing$bathrooms)] &lt;-1

table(clean_listing$beds) </code></pre>
<pre><code>## 
##     1     2     3     4     5     6     7     8     9    10    11    12 
## 17822  6856  3116  1677   730   444   151   162    58    86    17    19 
##    13    14    15    16 
##     4     5     3    44</code></pre>
<pre class="r"><code>clean_listing$beds[is.na(clean_listing$beds)] &lt;- 1</code></pre>
<ul>
<li>Price columns:<br />
Let’s assume that the NAs are actually zeros for all the price columns and replace all NA values with 0.</li>
</ul>
<pre class="r"><code>## Assuming that NAs in the price columns are 0
clean_listing$cleaning_fee[is.na(clean_listing$cleaning_fee)] &lt;- 0
clean_listing$security_deposit[is.na(clean_listing$security_deposit)] &lt;-
  0
clean_listing$weekly_price[is.na(clean_listing$weekly_price)] &lt;- 0
clean_listing$monthly_price[is.na(clean_listing$monthly_price)] &lt;- 0</code></pre>
<ul>
<li>Review_scores_rating:<br />
There are 7527 observations where the review_scores_rating is NA.Let’s Replace the NA values with the median value of the ratings.</li>
</ul>
<pre class="r"><code>## Replacing the NAs 0 % rating
clean_listing$review_scores_rating[is.na(clean_listing$review_scores_rating)] &lt;-  median(clean_listing$review_scores_rating, na.rm = TRUE)</code></pre>
<ul>
<li>host_response_rate:<br />
Host_reasponse_rate column has both “N/A” and “NA” values. First, let’s convert the records with “N/A” values to “NA” and then convert the NA records to “0%”. It would be helpful if this variable is numeric. To convert it to a Number variable, we need to remove the “%” sign first.</li>
</ul>
<pre class="r"><code># convert the records with &quot;N/A&quot; values to &quot;NA&quot;
levels(clean_listing$host_response_rate)[levels(clean_listing$host_response_rate) == &quot;N/A&quot;] &lt;- NA
# convert the NA records to &quot;0%&quot;
clean_listing$host_response_rate[is.na(clean_listing$host_response_rate)] &lt;- &quot;0%&quot;
# Remove the % sign
clean_listing$host_response_rate &lt;-
  gsub(&quot;\\%&quot;, replacement = &quot;&quot;, clean_listing$host_response_rate)
# Convert the variable to nemeric
clean_listing$host_response_rate &lt;-as.numeric(clean_listing$host_response_rate)</code></pre>
<ul>
<li>host_identity_verified:<br />
This Variable has categorical values of TRUE and FALSE. So, let’s assume the NA records are FALSE i.e. the records which do not have a value for this variable, the host identity is not verified.</li>
</ul>
<pre class="r"><code>clean_listing$host_identity_verified[is.na(clean_listing$host_identity_verified)] &lt;- &quot;f&quot;</code></pre>
<ul>
<li>host_has_profile_pic: This Variable has categorical values TRUE and FALSE. So, let’s assume the NA records are FALSE i.e. the records which do not have a value for this variable, the host has not uploaded a profile picture.</li>
</ul>
<pre class="r"><code>## Assuming that NAs in the host_has_profile_pic columns are False
clean_listing$host_has_profile_pic[is.na(clean_listing$host_has_profile_pic)] &lt;- &quot;f&quot;</code></pre>
<ul>
<li>host_listings_count: This Variable has numerical value.So, let’s assume the NA records are equal 1 since at least one listing is there for the host.</li>
</ul>
<pre class="r"><code>## Replacing the NAs with the 1
clean_listing$host_listings_count[is.na(clean_listing$host_listings_count)] &lt;- 1</code></pre>
<p>Let’s check again if any column has a NA value:</p>
<pre class="r"><code>sapply(clean_listing, function (x) sum(is.na(x)))</code></pre>
<pre><code>##                     id           accommodates     host_response_rate 
##                      0                      0                      0 
##      host_is_superhost   host_has_profile_pic host_identity_verified 
##                      0                      0                      0 
##    host_listings_count       instant_bookable          property_type 
##                      0                      0                      0 
##              room_type              bathrooms               bedrooms 
##                      0                      0                      0 
##                   beds               bed_type    cancellation_policy 
##                      0                      0                      0 
##       availability_365                  price           weekly_price 
##                      0                      0                      0 
##          monthly_price           cleaning_fee       security_deposit 
##                      0                      0                      0 
##      number_of_reviews   review_scores_rating 
##                      0                      0</code></pre>
<p>So, now we do not have any NA records.<br />
<br> 4. For the Property_Type Varaible, most of the listings are either an Aprtment or an independent House. There are a few listings for the rest of the categories.</p>
<pre class="r"><code>table(clean_listing$property_type)</code></pre>
<pre><code>## 
##          Apartment    Bed &amp; Breakfast               Boat 
##              13801                328                 44 
##     Boutique hotel           Bungalow              Cabin 
##                 23                455                 77 
##          Camper/RV    Casa particular             Castle 
##                109                  1                 10 
##               Cave             Chalet        Condominium 
##                  1                  4                917 
##               Dorm        Earth House        Guest suite 
##                128                  4                 25 
##         Guesthouse             Hostel              House 
##                560                 66              12736 
##                Hut             In-law             Island 
##                  8                  3                  1 
##         Lighthouse               Loft              Other 
##                  1                563                318 
##      Parking Space              Plane Serviced apartment 
##                  1                  1                 14 
##               Tent               Tipi          Townhouse 
##                 18                  4                769 
##              Train          Treehouse      Vacation home 
##                  1                  9                  9 
##              Villa               Yurt 
##                234                 10</code></pre>
<p><br> So, let’s keep only 3 categories for the property_type variable as below for simplicity:<br />
1. Apartment<br />
2. House<br />
3. Others</p>
<p><br> 5. Let’s check the price variable.</p>
<pre class="r"><code>summary(clean_listing$price)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    10.0    69.0   100.0   180.1   170.0 10000.0</code></pre>
<pre class="r"><code>quantile(clean_listing$price, probs = seq(0.1, 0.9, 0.1))</code></pre>
<pre><code>## 10% 20% 30% 40% 50% 60% 70% 80% 90% 
##  46  60  75  90 100 125 150 199 299</code></pre>
<p><br> Let’s restrict our analysis to those listings whose price is less or equal to $500/per night. The goal of this project is to understand the prices for the vast majority of the listings. We would not like our analysis to be influenced by some unusually expensive properties. <br></p>
<pre class="r"><code># take a subset of the records with price &lt;= 500
clean_listing &lt;-
  clean_listing %&gt;%
   filter(price &lt;= 500)
dim(clean_listing)</code></pre>
<pre><code>## [1] 29982    23</code></pre>
<p><br> So, now our current dataset has <strong>29,982</strong> observations which is 95% of the original dataset with <strong>31,253</strong> observations. <br><br> 6. Let’s check the cancellation_policy for the listings:</p>
<pre class="r"><code>table(clean_listing$cancellation_policy)</code></pre>
<pre><code>## 
##        flexible        moderate          strict super_strict_30 
##            9280            7638           13054               1 
## super_strict_60 
##               9</code></pre>
<p>Since there are only a few observations under the categories “super_strict_30” and “super_strict_60”, let’s change the cancellation_policy to “strict” for these observations.</p>
<pre class="r"><code># Change the few observations that have cancelation policy of super_strict_30 and super_strict_60 to strict
levels(clean_listing$cancellation_policy)[levels(clean_listing$cancellation_policy) ==&quot;super_strict_30&quot;] &lt;- &quot;strict&quot;
levels(clean_listing$cancellation_policy)[levels(clean_listing$cancellation_policy) ==&quot;super_strict_60&quot;] &lt;- &quot;strict&quot;</code></pre>
</div>
<div id="adding-new-features" class="section level1">
<h1><span class="header-section-number">6</span> Adding New Features</h1>
<p><strong>1. has_weekly_discount &amp; has_monthly_discount:</strong> <br> There is a weekly_price variable and a monthly_price vraiable. For, some of the listings, there are values for these two vraiables. Let’s add two new features based on these two variavle to see if there is a discount if someone is booking the listing weekly basis or a monthly basis.</p>
<pre class="r"><code># Add 2 new columns has_weekly_discount and has_monthly_discount
clean_listing$has_weekly_discount &lt;- 
ifelse(((clean_listing$price * 7) - clean_listing$weekly_price) &gt; 0 &amp; clean_listing$weekly_price!= 0, &quot;Yes&quot;, &quot;No&quot; )
clean_listing$has_monthly_discount &lt;- ifelse(((clean_listing$price * 30) - clean_listing$monthly_price) &gt; 0  &amp; clean_listing$monthly_price!= 0, &quot;Yes&quot;, &quot;No&quot; )</code></pre>
<p><strong>2. good_host_response:</strong> <br> Based on the existing variable “host_response_rate”, let’s add a new feature “good_host_response”. Considering, if a host is responding 60% of the time, then the host_response_rate is good.</p>
<pre class="r"><code>clean_listing$good_host_response &lt;- ifelse(clean_listing$host_response_rate  &gt; 60, &quot;Yes&quot;, &quot;No&quot; )</code></pre>
<p><br> <strong>Now, the data is ready for analysis.</strong></p>
</div>
<div id="exploratory-data-analysis" class="section level1">
<h1><span class="header-section-number">7</span> Exploratory Data Analysis</h1>
<p>Let’s summarize the vraiables with some visuals.Here, my goal is as below:<br />
<br> 1. Understand the variables individually<br />
2. Spot relationships between all the explanatory variables and the price<br />
<br><br> <strong>1. Understand the variables individually</strong> <br><br> <strong>1. Price:</strong><br />
Since we are working on understanding the Price for the Airbnb listings in LA, let’s first check what’s the price range for the listings in LA.</p>
<pre class="r"><code>ggplot(clean_listing, aes(x = price)) +
  geom_histogram(color = &#39;black&#39;,
                 fill = &#39;light blue&#39;,
                 na.rm = TRUE) +
  scale_x_continuous(limits = c(0, 500), breaks = seq(0, 500, 50)) +
  scale_y_continuous(limits = c(0, 6000), breaks = seq(0, 6000, 500))+
  ggtitle(&quot;Price Trends for Airbnb Listings in LA&quot;) </code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-25-1.png" width="672" /> <br> <strong>Conclusion:</strong> It looks like most of the Airbnb properties in LA are in the range of 50 - 120 dollars per night. There are only a few listing in higher price range. <br> <br> <strong>2. Property_Type &amp; Room_Type:</strong><br />
Let’s see what type of property are usually rented out as part of an Airbnb in LA.</p>
<pre class="r"><code>table(clean_listing$property_type, clean_listing$room_type)</code></pre>
<pre><code>##            
##             Entire home/apt Private room Shared room
##   Apartment            9015         4009         689
##   Others               2531         1684         306
##   House                5240         5878         630</code></pre>
<pre class="r"><code>ggplot(clean_listing, aes(x=property_type,fill=room_type)) +
  geom_bar(na.rm = TRUE)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-26-1.png" width="672" /> <br> <strong>Conclusion:</strong> For Airbnb, people usually rent out their entire home or entire apartment or even a private room in their house.Also, it is observed here that entire home or a private room is more in demand than a shared accomodation which is really understandable. <br><br> <strong>3. Bed_Type:</strong><br />
Let’s see what types of beds are mostly used in Airbnbs.</p>
<pre class="r"><code>ggplot(clean_listing, aes(x = bed_type)) +
  geom_bar(fill = &#39;light green&#39;, na.rm = TRUE)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-27-1.png" width="672" /> <br> <strong>Conclusion:</strong> Though the concept of Airbnb starterd with Airbeds, it looks like Real Reds are much more popular nowadays. <br><br> <strong>4.Cancellation_policy:</strong><br />
Let’s see what cancellation policy are more appropriate for an Airbnb in LA.</p>
<pre class="r"><code>ggplot(clean_listing, aes(x = cancellation_policy)) +
  geom_bar(fill = &#39;blue&#39;, na.rm = TRUE)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-28-1.png" width="672" /> <br> <strong>Conclusion:</strong> Hosts are usually strict regarding any cancellation which is quite natural because a cancellation means some loss in business. <br><br> <strong>5. Host_is_superhost:</strong><br />
Let’s see the ratio of Super Hosts vs Normal Host</p>
<pre class="r"><code>prop.table(table(clean_listing$host_is_superhost))</code></pre>
<pre><code>## 
##        f        t 
## 0.795077 0.204923</code></pre>
<pre class="r"><code>ggplot(clean_listing, aes(x = host_is_superhost)) +
  geom_bar(fill = &#39;light yellow&#39;)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-29-1.png" width="672" /> <br> <strong>Conclusion:</strong> Only 20% of the hosts in LA are identified as a “Super” host. <br><br> <strong>6. Host_identity_verified:</strong><br />
Let’s see if most of the host’s identity is verified in LA Airbnb</p>
<pre class="r"><code>prop.table(table(clean_listing$host_identity_verified))</code></pre>
<pre><code>## 
##         f         t 
## 0.3078514 0.6921486</code></pre>
<pre class="r"><code>ggplot(clean_listing, aes(x = host_identity_verified)) +
  geom_bar(fill = &#39;light blue&#39;)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-30-1.png" width="672" /> <br> <strong>Conclusion:</strong> 70% of the host’s identity is verified in LA and still there are 30% of the hosts whose identity is not yet verified and that’s alarming. <br><br> <strong>7. Instant_bookable:</strong><br />
Instant Book listings don’t require an approval from the host before they can be booked. Instead, guests can just choose their travel dates, book, and discuss check-in plans with the host.</p>
<pre class="r"><code>prop.table(table(clean_listing$instant_bookable))</code></pre>
<pre><code>## 
##         f         t 
## 0.7230005 0.2769995</code></pre>
<pre class="r"><code>ggplot(clean_listing, aes(x = instant_bookable)) +
  geom_bar(fill = &#39;light green&#39;)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-31-1.png" width="672" /> <br> <strong>Conclusion:</strong> Instant_booking is NOT opted by most of the hosts yet.But this feature can attract more guests since it can save some time. <br><br> <strong>8. has_monthly_discount:</strong></p>
<pre class="r"><code>prop.table(table(clean_listing$has_monthly_discount))</code></pre>
<pre><code>## 
##        No       Yes 
## 0.8082516 0.1917484</code></pre>
<pre class="r"><code>ggplot(clean_listing, aes(x = has_monthly_discount)) +
  geom_bar(fill = &#39;light blue&#39;)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-32-1.png" width="672" /> <br> Most of the host is not providing any monthly discount and it’s unlikely to book a listing for a month. <br><br> <strong>8. has_weekly_discount:</strong></p>
<pre class="r"><code>prop.table(table(clean_listing$has_weekly_discount))</code></pre>
<pre><code>## 
##        No       Yes 
## 0.8276633 0.1723367</code></pre>
<pre class="r"><code>ggplot(clean_listing, aes(x = has_weekly_discount)) +
  geom_bar(fill = &#39;light blue&#39;)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-33-1.png" width="672" /> <br> Again, weekly discount is also not available for most of the listings. <br> <br></p>
<p><strong>2. Spot relationships between the explanatory variables and price</strong><br />
<br><br> 1. Plot price vs number_of_reviews<br />
<br></p>
<pre class="r"><code>ggplot(clean_listing, aes(x = number_of_reviews, y = price)) +
  geom_point() +
  geom_smooth(method = lm, fullrange=TRUE)+
    scale_x_continuous(limits = c(0, 600), breaks = seq(0, 600, 100))</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-34-1.png" width="672" /> <br> It looks like usually the less price listings has more reviews which is expected since people usually look for some budget friendly properties. <br><br> 2. Plot price vs bedrooms<br />
<br></p>
<pre class="r"><code>ggplot(clean_listing, aes(x = factor(bedrooms), y = price)) +
  geom_boxplot(na.rm = TRUE) +
  ylim(50, 500)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-35-1.png" width="672" /> <br> As per the above plot results, the price for the listings with more bedrooms are usually more. That means a 1 bedroom apartment is less price than a 3 bedroom apartment and the result is as expected. <br><br> 3. Plot price vs bathrooms<br />
<br></p>
<pre class="r"><code>ggplot(clean_listing, aes(x = factor(bathrooms), y = price)) +
  geom_boxplot(na.rm = TRUE) +
  ylim(50, 500)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-36-1.png" width="672" /> <br> Again,as per the above plot results, the price for the listings with more bathrooms are usually more. That means a 2 bedroom apartment with 1 bath is less price than a 2 bedroom apartment with 2 baths and the result is as expected. <br><br> 4. Plot price vs cancellation_policy<br />
<br></p>
<pre class="r"><code>ggplot(clean_listing, aes(x = cancellation_policy, y = price)) +
  geom_boxplot(na.rm = TRUE) +
  ylim(50, 500)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-37-1.png" width="672" /> <br> Cancellation Policy does not influence the price much.So, a host can select a strict cancellation policy and choose the same price as a listing with a flexible cancellation policy. <br><br> 5. Plot price vs property_type<br />
<br></p>
<pre class="r"><code>  ggplot(clean_listing, aes(x = property_type, y = price)) +
  geom_boxplot(na.rm = TRUE) +
  ylim(00, 500)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-38-1.png" width="672" /> <br> As per the plot, the Mean price for each property type is at the range of $100 per night and the property type does not have a great influence on price. <br><br> 6. Plot price vs room_type<br />
<br></p>
<pre class="r"><code>ggplot(clean_listing, aes(x = room_type, y = price)) +
  geom_boxplot(na.rm = TRUE) +
  ylim(00, 500)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-39-1.png" width="672" /> <br> As per the plot, shared room has the least Mean price. The private rooms have a little higher Mean price than a shared accomodation, but quite less than the entire home. The entire home shows a lot more variation on average than a private room or a shared accomodation. <br><br> 7. Plot price vs bed_type<br />
<br></p>
<pre class="r"><code>ggplot(clean_listing, aes(x = bed_type, y = price)) +
  geom_boxplot(na.rm = TRUE) +
  ylim(00, 500)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-40-1.png" width="672" /> <br> The price is not much influenced by what type of Bed is there.Real Beds has a slightly more Mean price than any other types. <br><br> 8. Plot Price vs No. of Beds</p>
<pre class="r"><code>ggplot(clean_listing, aes(x = factor(beds), y = price)) +
  geom_boxplot(na.rm = TRUE) +
  ylim(0, 500)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-41-1.png" width="672" /> <br> As per the plot, it looks like with an increase in number of beds, the price is increasing. But then, there is a little drop in price for beds number equal to 8 or 10 or 16. <br><br> 9. Plot price vs accomodates <br></p>
<pre class="r"><code>ggplot(clean_listing, aes(x = factor(accommodates), y = price)) +
  geom_boxplot(na.rm = TRUE) +
  ylim(0, 500)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-42-1.png" width="672" /> <br> As per the plot, the price is increasing with an increase in the number of accomodates the host does allow for a listing. <br><br> 10. Plot price vs host_response_rate</p>
<pre class="r"><code>ggplot(clean_listing, aes(x = good_host_response, y = price)) +
  geom_bar(fill = &#39;light blue&#39;,na.rm = TRUE, stat = &quot;identity&quot;) +
  scale_y_continuous(limits = c(0, 500), breaks = seq(0, 500, 50))</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-43-1.png" width="672" /> <br> Apparently, host with better response can claim better price for their listing.</p>
</div>
<div id="create-a-model" class="section level1">
<h1><span class="header-section-number">8</span> Create a Model</h1>
<p>Let’s create a Linear Regresion Model to predict the price of an Airbnb Listing in LA. First, we will divide the records into training and test dataset. 80% of the Records goes to Training Set and the rest 20% to Test Set.</p>
<pre class="r"><code>dim(train_data) </code></pre>
<pre><code>## [1] 23986    26</code></pre>
<pre class="r"><code>dim(test_data)  </code></pre>
<pre><code>## [1] 5996   26</code></pre>
<p>Let’s build our model to predict price for the Budget Listings.</p>
<pre class="r"><code># Create a Linear Regression Model
lm_model &lt;-
  lm(
    price ~  host_identity_verified + instant_bookable + room_type +                 bedrooms + bathrooms +
      beds + availability_365 +
      accommodates + security_deposit + host_is_superhost                     +cleaning_fee + property_type
    + has_weekly_discount + has_monthly_discount
    + good_host_response + cancellation_policy ,
    data = train_data
  )
summary(lm_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ host_identity_verified + instant_bookable + 
##     room_type + bedrooms + bathrooms + beds + availability_365 + 
##     accommodates + security_deposit + host_is_superhost + cleaning_fee + 
##     property_type + has_weekly_discount + has_monthly_discount + 
##     good_host_response + cancellation_policy, data = train_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -334.16  -30.82   -7.74   19.80  470.05 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                  67.827745   1.447174  46.869  &lt; 2e-16 ***
## host_identity_verifiedt      -2.472554   0.843299  -2.932  0.00337 ** 
## instant_bookablet            -1.788636   0.862854  -2.073  0.03819 *  
## room_typePrivate room       -46.882663   0.987875 -47.458  &lt; 2e-16 ***
## room_typeShared room        -76.772182   1.876612 -40.910  &lt; 2e-16 ***
## bedrooms                     28.083060   0.724519  38.761  &lt; 2e-16 ***
## bathrooms                    14.257811   0.740938  19.243  &lt; 2e-16 ***
## beds                         -3.230659   0.449636  -7.185 6.91e-13 ***
## availability_365              0.042988   0.002848  15.092  &lt; 2e-16 ***
## accommodates                  7.188325   0.320357  22.439  &lt; 2e-16 ***
## security_deposit              0.025128   0.001211  20.741  &lt; 2e-16 ***
## host_is_superhostt            5.031987   0.972737   5.173 2.32e-07 ***
## cleaning_fee                  0.322851   0.010006  32.266  &lt; 2e-16 ***
## property_typeOthers           7.947201   1.118353   7.106 1.23e-12 ***
## property_typeHouse            6.636721   0.883311   7.513 5.96e-14 ***
## has_weekly_discountYes        7.384364   1.352018   5.462 4.76e-08 ***
## has_monthly_discountYes      -6.707560   1.312600  -5.110 3.24e-07 ***
## good_host_responseYes       -21.262682   1.019791 -20.850  &lt; 2e-16 ***
## cancellation_policymoderate  -8.684707   1.056477  -8.220  &lt; 2e-16 ***
## cancellation_policystrict    -7.304214   0.984920  -7.416 1.25e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 57.61 on 23966 degrees of freedom
## Multiple R-squared:  0.5914, Adjusted R-squared:  0.591 
## F-statistic:  1825 on 19 and 23966 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>plot(lm_model)</code></pre>
<p><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-46-1.png" width="672" /><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-46-2.png" width="672" /><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-46-3.png" width="672" /><img src="Capstone_Project_AirBnb_Proposal_files/figure-html/unnamed-chunk-46-4.png" width="672" /> <br><br> Let’s check the accuracy of this model. <br></p>
<pre class="r"><code>predict.lm_model &lt;- predict(lm_model, test_data)
head(predict.lm_model)</code></pre>
<pre><code>##      1539     13343     14238     25361      7203     11368 
##  77.76655  86.08840  88.88619 198.62701 132.27435  40.67321</code></pre>
<pre class="r"><code>head(test_data$price)</code></pre>
<pre><code>## [1]  70  44  99 249 119  38</code></pre>
<pre class="r"><code>SSE &lt;- sum((test_data$price - predict.lm_model) ^ 2)
SST &lt;- sum((test_data$price - mean(test_data$price)) ^ 2)
R_Squared_Value &lt;- 1 - SSE / SST
R_Squared_Value</code></pre>
<pre><code>## [1] 0.5842782</code></pre>
<p><br> The Adjusted R-Squared value for the linear regression model to predict the price of an Airbnb listing is <strong>0.591</strong>. For the test data set, the R-Squared value is <strong>0.5883346</strong> which is almost the same as the training set data.</p>
</div>
<div id="conclusion" class="section level1">
<h1><span class="header-section-number">9</span> Conclusion</h1>
<p>The scope of this project is to understand how the different features can influence the price and to create a tool to predict the price for an Airbnb listing. <br><br> Though, the current Linear Regression Model to predict the price is not perfect (R-Squared Value = 0.59), the model still would be helpful for providing a guidance for pricing.<br />
<br> Finally, let’s summarize our observations for the Airbnb dataset and build our own data story. <br><br> 1. Price for most of the listings in LA is in the range of $50 to $120 per night. <br><br> 2. Airbnb started with 3 Airbeds and with time Real Bed has gained more popularity. <br><br> 3. Most of the Airbnb hosts prefer a strict cancellation policy as a last minute cancellation can incur loss. <br><br> 4. Renting out an enire home or an entire apartment can be more beneficial to quote a better price than a private room or a shared one. <br><br> 5. Usually an Aprtment or an independent house is more in demand. Maybe that’s because many families prefer an Airbnb during a vacation to get a feeling and comfort of their own home. Aventurous options like a Boat or a Treehouse are there but less in number. <br><br> Now, let’s understand how the different features are related to the Price.</p>
<pre class="r"><code>coefficients(lm_model)</code></pre>
<pre><code>##                 (Intercept)     host_identity_verifiedt 
##                 67.82774521                 -2.47255371 
##           instant_bookablet       room_typePrivate room 
##                 -1.78863591                -46.88266293 
##        room_typeShared room                    bedrooms 
##                -76.77218225                 28.08305973 
##                   bathrooms                        beds 
##                 14.25781090                 -3.23065858 
##            availability_365                accommodates 
##                  0.04298835                  7.18832513 
##            security_deposit          host_is_superhostt 
##                  0.02512804                  5.03198681 
##                cleaning_fee         property_typeOthers 
##                  0.32285080                  7.94720067 
##          property_typeHouse      has_weekly_discountYes 
##                  6.63672068                  7.38436422 
##     has_monthly_discountYes       good_host_responseYes 
##                 -6.70755957                -21.26268160 
## cancellation_policymoderate   cancellation_policystrict 
##                 -8.68470732                 -7.30421411</code></pre>
<p><br> The below features have a <strong>Positive</strong> relation with price. i.e. while selecting a price for a new listing in LA, we can conclude that if the host is a “Super Host”, he can ask for a better price. Or, a house with more bedrooms and bathrooms (a bigger house) that accomodates more people can get better price. <br> 1. bathrooms<br />
2. availability_365<br />
3. security_deposit<br />
4. cleaning_fee<br />
5. property_typeHouse<br />
6. property_typeOthers<br />
7. has_weekly_discountYes<br />
8. bedrooms<br />
9. accommodates<br />
10. host_is_superhostt<br />
<br> <br> The below features have a <strong>Negative</strong> relation with price as per the data we are using for our analysis. i.e. That means the listings with Private rooms and Shared rooms can get less price. If the Host is Strict or Moderate with the cancellation policies, usually they ask for a lesser price. <br><br> 1. instant_bookablet<br />
2. room_typeShared room<br />
3. room_typePrivate room<br />
4. has_monthly_discountYes<br />
5. cancellation_policymoderate<br />
6. cancellation_policystrict<br />
7. good_host_responseYes<br />
8. beds<br />
9. host_identity_verifiedt</p>
</div>
<div id="future-scope" class="section level1">
<h1><span class="header-section-number">10</span> Future Scope</h1>
<ol style="list-style-type: decimal">
<li>Exploring and adding some more features could improve the current model for predicting price of an LA bsed Airbnb Listing. <br><br></li>
<li>There is a future scope to analyze and understand how the review scores are getting influenced by the different features and build a model to predict the review scores ratings. <br><br></li>
<li>Using the other available Datasets in Airbnb like the one for Reviews, we can also try to build a Reccomendation Model for the Guests. <br><br></li>
<li>We can try to categorize the Guests’ sentiments for each of the listings.<br />
<br><br> –The End–</li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
